# Generated by Django 5.2.16 on 2026-09-04 16:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0022_qa_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_service_date', models.DateField(blank=True, help_text="Date depreciation starts. Defaults to the asset's purchase date.", null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, help_text="Residual value floor. If blank, derived from the category policy's salvage %.", max_digits=12, null=True)),
                ('annual_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Per-asset annual WDV rate. If blank, the category policy rate is used.', max_digits=5, null=True)),
                ('is_depreciable', models.BooleanField(default=True)),
                ('opening_accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Accumulated depreciation already booked before go-live (for pre-owned assets).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='inventory.asset')),
            ],
            options={
                'ordering': ['asset__miczon_id'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('method', models.CharField(choices=[('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped'), ('LOST', 'Lost'), ('WRITTEN_OFF', 'Written Off')], default='SOLD', max_length=20)),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nbv_at_disposal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gain_loss', models.DecimalField(decimal_places=2, help_text='Proceeds − NBV at disposal (positive = gain).', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_financial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='accounts.assetfinancial')),
            ],
            options={
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rate', models.DecimalField(decimal_places=2, help_text='Annual WDV rate as a percentage, e.g. 33.33', max_digits=5)),
                ('salvage_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default salvage/residual value as a percentage of purchase cost.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('super_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_policy', to='inventory.supercategory')),
            ],
            options={
                'verbose_name_plural': 'Depreciation Policies',
                'ordering': ['super_category__name'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='POSTED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('opening_nbv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_nbv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='accounts.assetfinancial')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.depreciationrun')),
            ],
            options={
                'verbose_name_plural': 'Depreciation Entries',
                'ordering': ['-period_year', '-period_month', 'asset_financial__asset__miczon_id'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='accounts_de_period__dbc1fc_idx')],
                'unique_together': {('asset_financial', 'period_year', 'period_month')},
            },
        ),
    ]
