# Generated by Django 6.0.1 on 2026-01-08 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_by', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=20)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('returned_by', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.employee')),
            ],
        ),
    ]
