# Generated by Django 6.0 on 2026-01-09 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assetassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
