# Generated by Django 6.0 on 2026-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_assetassignment_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='sent_to_repair_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
