# Generated by Django 6.0 on 2026-03-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_assetactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetactionrequest',
            name='asset_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetactionrequest',
            name='action_type',
            field=models.CharField(choices=[('ADD', 'Add'), ('ASSIGN', 'Assign'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return'), ('REPAIR', 'Repair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assetactionrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.asset'),
        ),
    ]
