# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_assetactionrequest_asset_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Global Hardware Health Check', max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assetactionrequest',
            name='requested_device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HealthCheckResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SCRATCHED', 'Scratched'), ('CRACKED', 'Cracked'), ('NEEDS_REPAIR', 'Needs Repair')], max_length=30)),
                ('battery_life', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=30)),
                ('performance_rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_trail', to='inventory.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_check_responses', to='inventory.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inventory.healthchecksession')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'employee', 'asset')},
            },
        ),
    ]
