# Generated by Django 6.0 on 2026-05-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_asset_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetactionrequest',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
