# Generated by Django 5.2.16 on 2026-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_seed_super_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckresponse',
            name='compressor_motor_status',
            field=models.CharField(blank=True, default='QUIET_SMOOTH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='control_panel_remote',
            field=models.CharField(blank=True, default='ALL_FUNCTIONAL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='cooling_heating_perf',
            field=models.CharField(blank=True, default='OPTIMAL_TEMP', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='drawers_locks',
            field=models.CharField(blank=True, default='SMOOTH_FUNCTIONAL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='ergonomic_adjustment',
            field=models.CharField(blank=True, default='SMOOTH_MECHANISM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='filter_ventilation',
            field=models.CharField(blank=True, default='CLEAN_CLEAR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='legs_castors_base',
            field=models.CharField(blank=True, default='ALL_INTACT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='power_cord_plug',
            field=models.CharField(blank=True, default='INTACT_SAFE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='refrigerant_leak_check',
            field=models.CharField(blank=True, default='NO_LEAKS', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='structural_stability',
            field=models.CharField(blank=True, default='SOLID_STABLE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='surface_finish',
            field=models.CharField(blank=True, default='EXCELLENT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckresponse',
            name='upholstery_padding',
            field=models.CharField(blank=True, default='INTACT_CLEAN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='asset_tag_status',
            field=models.CharField(choices=[('INTACT_SCANNABLE', 'Intact & Scannable'), ('FADED_PEELING', 'Faded/Peeling'), ('MISSING', 'Missing')], default='INTACT_SCANNABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='battery_life',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('NOT_APPLICABLE', 'Not Applicable (N/A)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='network_functionality',
            field=models.CharField(blank=True, choices=[('CONNECTS_NORMALLY', 'Connects normally'), ('INTERMITTENT_CONNECTION', 'Intermittent connection'), ('FAILS_TO_CONNECT', 'Fails to connect')], default='CONNECTS_NORMALLY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='performance_rating',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='physical_condition',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD_MINOR_WEAR', 'Good (Minor wear)'), ('FAIR_SCRATCHES_DENTS', 'Fair (Noticeable scratches/dents)'), ('POOR_CRACKED_BROKEN', 'Poor (Cracked/Broken)')], default='GOOD_MINOR_WEAR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='ports_connectors',
            field=models.CharField(blank=True, choices=[('ALL_FUNCTIONAL', 'All functional'), ('LOOSE_CONNECTIONS', 'Loose connections'), ('VISIBLY_DAMAGED', 'Visibly damaged'), ('UNRESPONSIVE', 'Unresponsive')], default='ALL_FUNCTIONAL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='power_boot_status',
            field=models.CharField(blank=True, choices=[('BOOTS_NORMALLY', 'Boots normally'), ('SLOW_TO_BOOT', 'Slow to boot'), ('POWERS_NO_DISPLAY_OS', 'Powers on but no display/OS'), ('DOES_NOT_POWER_ON', 'Does not power on')], default='BOOTS_NORMALLY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckresponse',
            name='screen_condition',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SCRATCHED', 'Scratched'), ('CRACKED', 'Cracked'), ('NEEDS_REPAIR', 'Needs Repair'), ('NOT_APPLICABLE', 'Not Applicable (N/A)')], max_length=50, null=True),
        ),
    ]
