# Generated by Django 6.0 on 2026-07-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('qty', models.IntegerField(default=0)),
                ('reorder', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('IN', 'Stock IN'), ('OUT', 'Stock OUT')], max_length=10)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock_management.stockproduct')),
            ],
        ),
    ]
