# Generated by Django 6.0 on 2026-07-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
