export const STOCK_OPERATORS = [
  {
    id: 'bilal',
    name: 'Mr Bilal',
    initials: 'MB',
    role: 'Stock In-Charge',
    accent: '#2563eb',
    gradient: 'linear-gradient(135deg, #1d4ed8, #06b6d4)',
    bgLight: '#eff6ff',
    borderLight: '#bfdbfe',
    description: 'Inventory audits & stock dispatch operations',
  },
  {
    id: 'adnan',
    name: 'Mr Adnan',
    initials: 'MA',
    role: 'Stock In-Charge',
    accent: '#059669',
    gradient: 'linear-gradient(135deg, #047857, #10b981)',
    bgLight: '#f0fdf4',
    borderLight: '#bbf7d0',
    description: 'Inbound receipt & catalog registry',
  },
  {
    id: 'saqib',
    name: 'Mr Saqib',
    initials: 'MS',
    role: 'Stock In-Charge',
    accent: '#7c3aed',
    gradient: 'linear-gradient(135deg, #6d28d9, #a855f7)',
    bgLight: '#faf5ff',
    borderLight: '#e9d5ff',
    description: 'Warehouse distribution & stock reporting',
  },
  {
    id: 'usman',
    name: 'Mr Usman',
    initials: 'MU',
    role: 'Stock In-Charge',
    accent: '#ea580c',
    gradient: 'linear-gradient(135deg, #c2410c, #f59e0b)',
    bgLight: '#fff7ed',
    borderLight: '#fed7aa',
    description: 'Stock transactions & replenishment tracking',
  },
];
